"""add business_models table

Revision ID: 05c0b818b492
Revises: 9ebc15ec2833
Create Date: 2026-03-10 17:03:53.908132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '05c0b818b492'
down_revision: Union[str, Sequence[str], None] = '9ebc15ec2833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_models',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_proposition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unfair_advantage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revenue_streams', sa.JSON(), nullable=True),
    sa.Column('go_to_market', sa.JSON(), nullable=True),
    sa.Column('known_competitors', sa.JSON(), nullable=True),
    sa.Column('tech_stack_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_models')
    # ### end Alembic commands ###
