"""add newsletter_posts table

Revision ID: 19f197288f26
Revises: 05c0b818b492
Create Date: 2026-03-11 15:51:40.509543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '19f197288f26'
down_revision: Union[str, Sequence[str], None] = '05c0b818b492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_posts',
    sa.Column('subject_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preview_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('markdown_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_posts')
    # ### end Alembic commands ###
