"""Add article_insights table

Revision ID: 95be2f05dfec
Revises: aee390d06b7a
Create Date: 2026-03-09 16:33:59.539795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '95be2f05dfec'
down_revision: Union[str, Sequence[str], None] = 'aee390d06b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_insights',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('business_signals', sa.JSON(), nullable=True),
    sa.Column('market_facts', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_insights')
    # ### end Alembic commands ###
