"""Add candidates table

Revision ID: 9ebc15ec2833
Revises: 95be2f05dfec
Create Date: 2026-03-10 14:34:34.121445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9ebc15ec2833'
down_revision: Union[str, Sequence[str], None] = '95be2f05dfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('archetype', sa.Enum('META_TREND', 'FRICTION_POINT', 'RABBIT_HOLE', name='candidatearchetype'), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why_now', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('one_liner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_customer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_to_solve', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solution_overview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supporting_article_ids', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
