"""add selected_candidate_id to runs and selected to candidates

Revision ID: febc3ea96545
Revises: ef0b4b623dd6
Create Date: 2026-03-12 15:09:26.010047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'febc3ea96545'
down_revision: Union[str, Sequence[str], None] = 'ef0b4b623dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_candidate_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_runs_selected_candidate_id', 'candidates', ['selected_candidate_id'], ['id'])

    # Backfill: for each run, select the highest-scoring candidate
    conn = op.get_bind()

    # Find the best candidate (highest score) per run
    best_per_run = conn.execute(sa.text("""
        SELECT c.run_id, c.id AS candidate_id
        FROM candidates c
        INNER JOIN (
            SELECT run_id, MAX(score) AS max_score
            FROM candidates
            GROUP BY run_id
        ) best ON c.run_id = best.run_id AND c.score = best.max_score
        GROUP BY c.run_id
    """)).fetchall()

    for run_id, candidate_id in best_per_run:
        conn.execute(
            sa.text("UPDATE candidates SET selected = 1 WHERE id = :cid"),
            {"cid": candidate_id},
        )
        conn.execute(
            sa.text("UPDATE runs SET selected_candidate_id = :cid WHERE id = :rid"),
            {"cid": candidate_id, "rid": run_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_runs_selected_candidate_id', type_='foreignkey')
        batch_op.drop_column('selected_candidate_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
